---
# generate-discovery-iso tasks

- name: Get infra-env image-url
  uri:
    url: "http://{{ assisted_installer_host }}:{{ assisted_installer_port }}/api/assisted-install/v2/infra-envs/{{ ai_infraenv_id }}/downloads/image-url"
    method: Get
    body_format: json
    status_code: [200]
    return_content: true
  register: infraenv_image_url

- name: Download discovery ISO
  get_url:
    url: "{{ infraenv_image_url.json.url }}"
    dest: "{{ http_store_path }}/data/discovery.iso"
    timeout: 60

- name: Set discovery.iso password
  block:
    - name: Backup original discovery.iso
      copy:
        src: "{{ http_store_path }}/data/discovery.iso"
        dest: "{{ http_store_path }}/data/discovery-backup.iso"
        remote_src: true
        mode: 0644

    - name: Checkout assisted-service repo
      git:
        repo: https://github.com/openshift/assisted-service.git
        dest: /root/assisted-service
        version: master

    - name: Create new discovery iso with password
      shell: 'echo -e "${DISCOVERY_ISO_PASSWORD}" | /root/assisted-service/docs/change-iso-password.sh {{ http_store_path }}/data/discovery.iso'
      environment:
        - DISCOVERY_ISO_PASSWORD: discovery_iso_password

    - name: Copy discovery_with_password.iso to discovery.iso
      copy:
        src: "{{ http_store_path }}/data/discovery_with_password.iso"
        dest: "{{ http_store_path }}/data/discovery.iso"
        remote_src: true
        mode: 0644

  when: discovery_iso_password is defined

- name: Symlink for /iso/discovery.iso
  ansible.builtin.file:
    src: ../discovery.iso
    dest: "{{ http_store_path }}/data/iso/discovery.iso"
    state: link
